Repository microsoft/coe-starter-kit, pull requests merged in 2021-05, with the labels that each got.

#255 Fixes #238 - Production Deploy without Build
  Theming/deploy-prod-Theming.yml
Labels: coe-starter-kit, pipelines

#253 Fixes #238 - Production Deploy without Build
  PowerPlatformGitHubALM/deploy-prod-ALMAcceleratorForMakers.yml
Labels: coe-starter-kit, pipelines

#252 Fixes #238 - Production Deploy without Build
  ALMAcceleratorSampleSolution/deploy-prod-ALMAcceleratorSampleSolution.yml
Labels: coe-starter-kit, pipelines

#244 Fixes #238 - Production Deploy without Build
  CenterofExcellenceNurtureComponents/deploy-prod-CenterofExcellenceNurtureComponents.yml
Labels: coe-starter-kit, pipelines

#245 Fixes #238 - Production Deploy without Build
  CenterofExcellenceMicrosoftTeamsIntegration/deploy-prod-CenterofExcellenceMicrosoftTeamsIntegration.yml
Labels: coe-starter-kit, pipelines

#248 Fixes #238 - Production Deploy without Build
  CenterofExcellenceCoreComponentsTeams/deploy-prod-CenterofExcellenceCoreComponentsTeams.yml
Labels: coe-starter-kit, pipelines

#249 Fixes #238 - Production Deploy without Build
  CenterofExcellenceCoreComponents/deploy-prod-CenterofExcellenceCoreComponents.yml
Labels: coe-starter-kit, pipelines

#247 Fixes #238 - Production Deploy without Build
  CenterofExcellenceInnovationBacklog/deploy-prod-CenterofExcellenceInnovationBacklog.yml
Labels: coe-starter-kit, pipelines

#250 Fixes #238 - Production Deploy without Build
  CenterofExcellenceAuditLogs/deploy-prod-CenterofExcellenceAuditLogs.yml
Labels: coe-starter-kit, pipelines

#251 Fixes #238 - Production Deploy without Build
  CenterofExcellenceAuditComponents/deploy-prod-CenterofExcellenceAuditComponents.yml
Labels: coe-starter-kit, pipelines

#254 Fixes #238 - Production Deploy without Build
  PowerPlatformDevOpsALM/deploy-prod-ALMAcceleratorForAdvancedMakers.yml
Labels: alm-accelerator, pipelines

#246 Fixes #238 - Production Deploy without Build
  CenterofExcellenceMakerJourney/deploy-prod-CenterofExcellenceMakerJourney.yml
Labels: coe-starter-kit, pipelines

#286 Fixes #238 - GitHub Fix
  PowerPlatformGitHubALM/deploy-prod-ALMAcceleratorForMakers.yml
Labels: coe-starter-kit, pipelines

#285 Fixes #238 - GitHub Fix
  ALMAcceleratorSampleSolution/deploy-prod-ALMAcceleratorSampleSolution.yml
Labels: coe-starter-kit, pipelines

#283 Fixes #238 - GitHub Fix
  PowerPlatformDevOpsALM/deploy-prod-ALMAcceleratorForAdvancedMakers.yml
Labels: coe-starter-kit, pipelines

#282 Fixes #238 - GitHub Fix
  CenterofExcellenceAuditComponents/deploy-prod-CenterofExcellenceAuditComponents.yml
Labels: coe-starter-kit, pipelines

#281 Fixes #238 - GitHub Fix
  CenterofExcellenceAuditLogs/deploy-prod-CenterofExcellenceAuditLogs.yml
Labels: coe-starter-kit, pipelines

#280 Fixes #238 - GitHub Fix
  CenterofExcellenceCoreComponents/deploy-prod-CenterofExcellenceCoreComponents.yml
Labels: coe-starter-kit, pipelines

#279 Fixes #238 - GitHub Fix
  Theming/deploy-prod-Theming.yml
Labels: coe-starter-kit, pipelines

#278 Fixes #238 - GitHub Fix
  CenterofExcellenceNurtureComponents/deploy-prod-CenterofExcellenceNurtureComponents.yml
Labels: coe-starter-kit, pipelines

#277 Fixes #238 - GitHub Fix
  CenterofExcellenceCoreComponentsTeams/deploy-prod-CenterofExcellenceCoreComponentsTeams.yml
Labels: coe-starter-kit, pipelines

#276 Fixes #238 - GitHub Fix
  CenterofExcellenceInnovationBacklog/deploy-prod-CenterofExcellenceInnovationBacklog.yml
Labels: coe-starter-kit, pipelines

#275 Fixes #238 - GitHub Fix
  CenterofExcellenceMakerJourney/deploy-prod-CenterofExcellenceMakerJourney.yml
Labels: coe-starter-kit, pipelines

#274 Fixes #238 - GitHub Fix
  CenterofExcellenceMicrosoftTeamsIntegration/deploy-prod-CenterofExcellenceMicrosoftTeamsIntegration.yml
Labels: coe-starter-kit, pipelines

#302 update required permissions on Service Connection
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/SetServiceConnectionPermissions.png
  PowerPlatformDevOpsALM/SETUPGUIDE.md
Labels: alm-accelerator, documentation

#304 Fixes #303: Fix for branch creation instructions
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210507110620258.png
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210507110801961.png
  PowerPlatformDevOpsALM/SETUPGUIDE.md
Labels: alm-accelerator, documentation

#327 Fixes #324
  PowerPlatformDevOpsALM/.attachments/SAMPLESOLUTIONSETUPGUIDE/image-20210510163520532.png
  PowerPlatformDevOpsALM/.attachments/SAMPLESOLUTIONSETUPGUIDE/image-20210510163722833.png
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210510163520532.png
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210510163722833.png
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210510163831717.png
  PowerPlatformDevOpsALM/.attachments/SETUPGUIDE/image-20210510163834521.png
  PowerPlatformDevOpsALM/SAMPLESOLUTIONSETUPGUIDE.md
  PowerPlatformDevOpsALM/SETUPGUIDE.md
Labels: alm-accelerator, documentation

#448 Fixes #192 Removed Upgrade Toggle
  ALMAcceleratorForAdvancedMakers/SolutionPackage/AppModuleSiteMaps/cat_AppUserSettingManagement/AppModuleSiteMap.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/AppModuleSiteMaps/cat_AppUserSettingManagement/AppModuleSiteMap_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/AppModules/cat_AppUserSettingManagement/AppModule.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/AppModules/cat_AppUserSettingManagement/AppModule_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4.meta.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Connections/Connections.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Entropy/AppCheckerResult.sarif
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Entropy/Entropy.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Entropy/checksum.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Components/Header_3.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Components/Preloader_1.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Components/TabControl_1.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/EditorState/Home.editorstate.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/Src/Home.fx.yaml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/pkgs/Components/Header.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/pkgs/Components/Preloader.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/pkgs/Components/TabControl.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/CanvasApps/cat_poweropsdevopsedition_7f3f4_DocumentUri_msapp_src/pkgs/Wadl/CustomAzureDevOps.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Connectors/cat_5Fcustomazuredevops.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Connectors/cat_5Fcustomazuredevops_openapidefinition.json
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/Entity.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/card/{ee8c40dc-6208-4563-9bc6-a2ed27939a21}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/card/{ee8c40dc-6208-4563-9bc6-a2ed27939a21}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/main/{6b1f4136-33d7-47bc-8d12-8030b9f127ce}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/main/{6b1f4136-33d7-47bc-8d12-8030b9f127ce}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/quick/{c12f7787-a4f4-47e2-998f-2a47b1113675}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/FormXml/quick/{c12f7787-a4f4-47e2-998f-2a47b1113675}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/RibbonDiff.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{822f92fb-aec1-4df6-920b-636a124e69b4}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{844c27d5-0d1d-4122-bd96-8716489fb05f}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{8f681df5-4ed9-48f5-9118-387fa137a5b5}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{bc33ce55-6e1e-46ad-a3b9-9c021c9536b7}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{bf113a54-5b7f-405e-97c3-44b24fe28f17}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{c3015a84-cb46-4d6a-9bad-2583a128c773}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_AppUserSetting/SavedQueries/{cfdc0825-5506-eb11-a813-000d3a56b702}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/Entity.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/card/{98953032-83c5-4ab7-b2e8-6e1909702f2f}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/card/{98953032-83c5-4ab7-b2e8-6e1909702f2f}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/main/{87e90f2a-6d3d-46cc-af42-a1b9d0620fa4}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/main/{87e90f2a-6d3d-46cc-af42-a1b9d0620fa4}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/quick/{868be4ab-1eec-44e8-875a-5f9518b0500e}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/FormXml/quick/{868be4ab-1eec-44e8-875a-5f9518b0500e}_managed.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/RibbonDiff.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{022b2542-c50f-434a-abb0-77d9def76445}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{2cf4d2aa-08c6-4ea2-97b5-563e4c3351e3}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{4d646d38-6345-4103-aa95-1f59a9c61bc4}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{6494a1ef-b08b-40b8-a0c4-208810b877af}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{68407ce4-5206-eb11-a813-000d3a56b702}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{b9852a94-a331-4bd6-b6a3-a88c29a90144}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Entities/cat_UserSetting/SavedQueries/{c1a248b1-bef9-46b5-bb49-24f3e57643bf}.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Customizations.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships/BusinessUnit.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships/Owner.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships/SystemUser.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships/Team.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Relationships/cat_AppUserSetting.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Other/Solution.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Roles/ALM Power App Access.xml
  ALMAcceleratorForAdvancedMakers/SolutionPackage/Workflows/GetEnvironmentSolutions-BD40F612-41FF-EA11-A815-000D3A1ABE26.json.data.xml
Labels: alm-accelerator, enhancement

#462 Fixes #361 and Fixes #452
  ALMAcceleratorForAdvancedMakers/deploy-prod-ALMAcceleratorForAdvancedMakers.yml
  ALMAcceleratorForAdvancedMakers/deploy-test-ALMAcceleratorForAdvancedMakers.yml
  ALMAcceleratorForAdvancedMakers/deploy-validation-ALMAcceleratorForAdvancedMakers.yml
Labels: alm-accelerator, pipelines

#464 Fixes #361 and Fixes #452
  Theming/deploy-prod-Theming.yml
  Theming/deploy-test-Theming.yml
  Theming/deploy-validation-Theming.yml
Labels: alm-accelerator, pipelines

#463 Fixes #361 and Fixes #452
  CenterofExcellenceCoreComponentsTeams/deploy-prod-CenterofExcellenceCoreComponentsTeams.yml
  CenterofExcellenceCoreComponentsTeams/deploy-test-CenterofExcellenceCoreComponentsTeams.yml
  CenterofExcellenceCoreComponentsTeams/deploy-validation-CenterofExcellenceCoreComponentsTeams.yml
Labels: alm-accelerator, pipelines

#461 Fixes #361 and Fixes #452
  CenterofExcellenceNurtureComponents/deploy-prod-CenterofExcellenceNurtureComponents.yml
  CenterofExcellenceNurtureComponents/deploy-test-CenterofExcellenceNurtureComponents.yml
  CenterofExcellenceNurtureComponents/deploy-validation-CenterofExcellenceNurtureComponents.yml
Labels: alm-accelerator, pipelines

#460 Fixes #361 and Fixes #452
  ALMAcceleratorForMakers/deploy-prod-ALMAcceleratorForMakers.yml
  ALMAcceleratorForMakers/deploy-test-ALMAcceleratorForMakers.yml
  ALMAcceleratorForMakers/deploy-validation-ALMAcceleratorForMakers.yml
Labels: alm-accelerator, pipelines

#458 Fixes #361 and Fixes #452
  CenterofExcellenceAuditComponents/deploy-prod-CenterofExcellenceAuditComponents.yml
  CenterofExcellenceAuditComponents/deploy-test-CenterofExcellenceAuditComponents.yml
  CenterofExcellenceAuditComponents/deploy-validation-CenterofExcellenceAuditComponents.yml
Labels: alm-accelerator, pipelines

#457 Fixes #361 and Fixes #452
  CenterofExcellenceAuditLogs/deploy-prod-CenterofExcellenceAuditLogs.yml
  CenterofExcellenceAuditLogs/deploy-test-CenterofExcellenceAuditLogs.yml
  CenterofExcellenceAuditLogs/deploy-validation-CenterofExcellenceAuditLogs.yml
Labels: alm-accelerator, pipelines

#456 Fixes #361 and Fixes #452
  CenterofExcellenceCoreComponents/deploy-prod-CenterofExcellenceCoreComponents.yml
  CenterofExcellenceCoreComponents/deploy-test-CenterofExcellenceCoreComponents.yml
  CenterofExcellenceCoreComponents/deploy-validation-CenterofExcellenceCoreComponents.yml
Labels: alm-accelerator, pipelines

#455 Fixes #361 and Fixes #452
  CenterofExcellenceInnovationBacklog/deploy-prod-CenterofExcellenceInnovationBacklog.yml
  CenterofExcellenceInnovationBacklog/deploy-test-CenterofExcellenceInnovationBacklog.yml
  CenterofExcellenceInnovationBacklog/deploy-validation-CenterofExcellenceInnovationBacklog.yml
Labels: alm-accelerator, pipelines

#454 Fixes #361 and Fixes #452
  CenterofExcellenceMakerJourney/deploy-prod-CenterofExcellenceMakerJourney.yml
  CenterofExcellenceMakerJourney/deploy-test-CenterofExcellenceMakerJourney.yml
  CenterofExcellenceMakerJourney/deploy-validation-CenterofExcellenceMakerJourney.yml
Labels: alm-accelerator, pipelines

#453 Fixes #361 and Fixes #452
  CenterofExcellenceMicrosoftTeamsIntegration/deploy-prod-CenterofExcellenceMicrosoftTeamsIntegration.yml
  CenterofExcellenceMicrosoftTeamsIntegration/deploy-test-CenterofExcellenceMicrosoftTeamsIntegration.yml
  CenterofExcellenceMicrosoftTeamsIntegration/deploy-validation-CenterofExcellenceMicrosoftTeamsIntegration.yml
Labels: alm-accelerator, pipelines

#475 Fixes #380 - Document Updates for 1.0.20210521.1
  ALMAcceleratorForAdvancedMakers/.attachments/GETTINGSTARTED/image-20210303085710535.png
  ALMAcceleratorForAdvancedMakers/.attachments/GETTINGSTARTED/image-3ccc9c10-4cd7-4188-9881-952bba2701dc.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524091622017.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524091948116.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524092126797.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524095158923.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524101653983.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524101705475.png
  ALMAcceleratorForAdvancedMakers/.attachments/PIPELINESYNCGUIDE/image-20210524102603951.png
  ALMAcceleratorForAdvancedMakers/.attachments/SAMPLESOLUTIONSETUPGUIDE/image-20210506145049512.png
  ALMAcceleratorForAdvancedMakers/.attachments/SAMPLESOLUTIONSETUPGUIDE/image-20210506145231393.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210506151302121.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210506151536128.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210506152930801.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210524110307135.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210524113423011.png
  ALMAcceleratorForAdvancedMakers/.attachments/SETUPGUIDE/image-20210524113929989.png
  ALMAcceleratorForAdvancedMakers/PIPELINESYNCGUIDE.md
  ALMAcceleratorForAdvancedMakers/SAMPLESOLUTIONSETUPGUIDE.md
  ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md
  ALMAcceleratorForAdvancedMakers/USERGUIDE.md
Labels: alm-accelerator, documentation

#487 Fixes #361 and Fixes #452
  ALMAcceleratorSampleSolution/deploy-prod-ALMAcceleratorSampleSolution.yml
  ALMAcceleratorSampleSolution/deploy-test-ALMAcceleratorSampleSolution.yml
  ALMAcceleratorSampleSolution/deploy-validation-ALMAcceleratorSampleSolution.yml
Labels: alm-accelerator, pipelines

#488 Fixes #363
  ALMAcceleratorSampleSolution/ConfigurationMigrationData/[Content_Types].xml
  ALMAcceleratorSampleSolution/ConfigurationMigrationData/data.xml
  ALMAcceleratorSampleSolution/ConfigurationMigrationData/data_schema.xml
Labels: alm-accelerator, bug

#511 Fixes #380
  ALMAcceleratorForAdvancedMakers/SAMPLESOLUTIONSETUPGUIDE.md
  ALMAcceleratorForAdvancedMakers/SETUPGUIDE.md
Labels: alm-accelerator, documentation

#529 Fixed #435
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06.meta.xml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/CanvasManifest.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Entropy/AppCheckerResult.sarif
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Entropy/Entropy.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Entropy/checksum.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/App.fx.yaml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/Components/Component1.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/EditorState/Screen1.editorstate.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/EditorState/scrImpact.editorstate.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/EditorState/scrMain.editorstate.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/EditorState/scrPrebuiltConnectors.editorstate.json
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/Screen1.fx.yaml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/scrImpact.fx.yaml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/scrMain.fx.yaml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/Src/scrPrebuiltConnectors.fx.yaml
  CenterofExcellenceCoreComponents/SolutionPackage/CanvasApps/admin_dlpeditorv2_fcf06_DocumentUri_msapp_src/pkgs/TableDefinitions/Makers.json
  CenterofExcellenceCoreComponents/SolutionPackage/Workflows/AdminSyncTemplatev3Connectors-7E1DDB35-613D-EB11-A813-000D3A8F4AD6.json
  CenterofExcellenceCoreComponents/SolutionPackage/Workflows/AdminSyncTemplatev3Flows-D9F8DF64-C838-EB11-A813-000D3A1BB495.json
  CenterofExcellenceCoreComponents/SolutionPackage/Workflows/CLEANUP-AdminSyncTemplatev3ConnectionStatus-D753F10F-F03E-EB11-A813-000D3A8F4AD6.json.data.xml
Labels: coe-starter-kit, core-components
